name: Floyd James Argüello
description: "Floyd James Argüello's blog about coding."
meta_description: "Floyd James Argüello"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://meta.fja.io'
google_analytics: 'UA-59235159-1'

url:            http://meta.fja.io
production_url : http://meta.fja.io
author:         'Floyd James Λrgüello'

gems:
  - jekyll-sitemap
